[package]
name = "polaris_macro_utils"
version = "0.0.1"
description = "Shared utilities for Polaris procedural macro crates."
edition = "2024"
keywords = []

[lints]
workspace = true

[dependencies]
proc-macro2 = "1"
quote = "1"
proc-macro-crate = "3"
