[package]
name = "system_macros"
version = "0.0.1"
description = "Macros for polaris_system crate."
edition = "2024"
keywords = []

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
