name: CI

on:
  pull_request:
    branches: [main]
    paths:
      - "crates/**/*.rs"
      - "examples/**/*.rs"
      - "**/Cargo.toml"
      - "Cargo.lock"
      - "Makefile.toml"
      - ".clippy.toml"
      - ".github/workflows/ci.yml"
      - "**/*.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.93.0"
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-make
        uses: taiki-e/install-action@cargo-make

      - name: Run tests
        run: cargo make test

      - name: Check examples
        run: cargo check --manifest-path examples/Cargo.toml
